services:
  astro:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4321:4321"           # Exponemos el puerto 4321
    environment:
      NODE_ENV: production
    restart: unless-stopped
    command: ["npm", "run", "preview", "--", "--host", "0.0.0.0"]
